version: '3'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: 
      POSTGRES_DB: 
      POSTGRES_PASSWORD: 
    ports:
        - :
  redis:
    image: 'redis:7-alpine'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - :
