services:
  app:
    image: meme-server:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - db
      - redis
    ports:
      - '8080:8080'
    # user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
    command: ["serve", "--env", "development", "--hostname", "0.0.0.0", "--port", "8080"]
  migrate:
    image: meme-server:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - db
    command: ["migrate", "--yes"]
    deploy:
      replicas: 0
  revert:
    image: meme-server:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - db
    command: ["migrate", "--revert", "--yes"]
    deploy:
      replicas: 0
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: meme-server-user
      POSTGRES_DB: memes
      POSTGRES_PASSWORD: supersecret01
    ports:
        - 5432:5432
  redis:
    image: 'redis:7-alpine'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
